ansible: revert static node wait logic

diff --git a/ydb-ansible/roles/ydbd_static/templates/wait_static.j2 b/ydb-ansible/roles/ydbd_static/templates/wait_static.j2
--- a/ydb-ansible/roles/ydbd_static/templates/wait_static.j2
+++ b/ydb-ansible/roles/ydbd_static/templates/wait_static.j2
@@ -15,22 +15,22 @@ export PATH
 
 COUNTER=0
 while true; do
-    sleep 10
     ydb --ca-file ${CAFILE} -e ${DB_ENDPOINT} -d ${DB_DOMAIN} --user root --no-password discovery list  >/dev/null 2>&1
     RESULT=$?
     if [ $RESULT -eq 0 ]; then
         exit 0
     fi
     COUNTER=$((COUNTER + 1))
-    if [ $COUNTER -gt 18 ]; then
+    if [ $COUNTER -gt 36 ]; then
         ydb --ca-file ${CAFILE} -e ${DB_ENDPOINT} -d ${DB_DOMAIN} --user root --no-password discovery list >&2
         RESULT=$?
         if [ $RESULT -eq 0 ]; then
             exit 0
         fi
-        echo "ERROR: storage node did not appear in the defined interval" >&2
+        echo "ERROR: storage node did not appear in 3 minutes" >&2
         exit 1
     fi
+    sleep 5
 done
 
 # End Of File
